version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

branches:
  only:
    - master

build_script:
  - cmd: dotnet restore src\SharpSPIRVCross.sln
  - cmd: dotnet pack -c Release src\SharpSPIRVCross\SharpSPIRVCross.csproj

artifacts:
- path: bin\Release\Packages\*.nupkg
  name: Nugets Artifacts

deploy:
- provider: NuGet
  server: https://www.myget.org/F/vortice/api/v2/package
  api_key:
    secure: rVfu/HYGH96xeQfy+gRBC/ovHCheQKTjwIeNIE9HlpkN6e4/YtPUqn5f036pSlmi
  skip_symbols: false
  symbol_server: https://www.myget.org/F/vortice/api/v2/package
  artifact: Nugets Artifacts
